services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dcfv147
      POSTGRES_DB: todos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: todos
      DB_PASSWORD: dcfv147
      DB_PORT: 5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: